### ISSUE TITLE
Will this work for React apps?

### ISSUE THREAD

**Issue by mackbrowne** [serut/meteor-coverage#49]
Hi, 

I'm trying to use this plugin with the meteor example apphttps://github.com/meteor/todos (react branch).  Is this even possible?  I've tried with little succuss so far, just trying to run the basic tests that come with the repo.

If not, is there any tool out there that will supply istanbul-style coverage for react / meteor apps?

Thanks!

**Comment by serut** [comment]
Yes it works but it's not so easy if you are not experimented with meteor tests...  
This library is agnostic of which framework you are using, it's kind of probe that collects coverage when you enable it.
This pr may help you to bootstrap coverage https://github.com/apollographql/meteor-starter-kit/pull/34

**Comment by mackbrowne** [comment]
Thanks for the quick reply.

I looked at your PR and managed to get the tests to run, also i am showing a web-report at localhost:3000/coverage.  However, I can't seem to get this report to save, or stick around.

I've tried adding to .coverage.json.... doesn't save anything in the ".coverage" folder. 

     "remapFormat": ["html"],
     "output": "./.coverage"

Test command in package.json is 
 TEST_BROWSER_DRIVER=nightmare meteor test --once --settings settings.coverage.json --driver-package dispatch:mocha


I feel like i"m really close to getting this to work.  My goal is to have the coverage report added to circleCI, at least now I can confirm the coverage is working, I just need to figure out how to save it for later :)

Thanks again!

**Comment by serut** [comment]
`spacejam` is the only way to automatize the output file that you can send to circle.ci.
Feel free to share your codebase to see why `spacejam` fails to run on your project

**Comment by mackbrowne** [comment]
Hey, thanks for taking a look.

Here is the Repo in it's current state:
https://github.com/mackbrowne/todos/tree/coverage

I'm using "meteor npm test" to run.  From there I need to go to localhost:3000 to run the tests, and then localhost:3000/coverage to see the report.

My attempts with spacejam, I replaced the npm test script with:

spacejam test --coverage 'out_lcovonly out_coverage out_html' --driver-package practicalmeteor:mocha-console-runner

Unfortunately this had a whole bunch of errors, and would crash.

I'm soo close, thank you again for the quick replies!!

**Comment by mackbrowne** [comment]
Hey @serut,

Was that branch I created enough to debug with? Would you like me to setup something else?  I want to make this as-little-work-as-possible for you.  I appreciate the help so I want to make it easy for you any way i can.

**Comment by serut** [comment]
Hello !

Yesterday I pushed a repository https://github.com/serut/meteor-react-apollo-test-coverage-starter-kit that contains apollo meteor and react and everything works as expected. It's a repository a lot simpler that meteor-todo, and I still not commit some React tests with enzyme, but I think it works.

However, I tryed with meteor-todo and there is a problem on launch and I don't have any clue of what's wrong..

**Comment by mackbrowne** [comment]
Ok i'll take a look at your repo, you were having issues with spacejam I assume?

**Comment by mackbrowne** [comment]
@serut I tried loading your repo.  Tried

"meteor npm run coverage" ,  I got very similar errors to what I was seeing in my repo.

Either way, with your help I've been able to see the results in istanbul through the /coverage url. Thank you.

You are 100% sure there is no way for me to export this coverage data without spacejam?  There's no temp file it's being stored in that I could use a dirty shell script to copy out?

**Comment by serut** [comment]
> I got very similar errors to what I was seeing in my repo.

Travis told me everything is working: https://travis-ci.org/serut/meteor-react-apollo-test-coverage-starter-kit
And you can see the code report: https://codecov.io/gh/serut/meteor-react-apollo-test-coverage-starter-kit
Did you run `meteor npm install` ? The [travis.yml](https://github.com/serut/meteor-react-apollo-test-coverage-starter-kit/blob/master/.travis.yml) file tells you everything about testing the project

> You are 100% sure there is no way for me to export this coverage data without spacejam? There's no temp file it's being stored in that I could use a dirty shell script to copy out?

No, you just need an headless browser that connects to the test page and to detect when tests succeed. Spacejam uses phantomjs under the hood. You can see on [the phantomjs coverage script](https://github.com/serut/spacejam/blob/windows-suppport-rc4/lib/phantomjs-test-in-console-with-coverage.coffee#L52) what happens : 
- tests succeed
- phantomjs runs `Package['meteor']['Meteor'].someCoverageCommand` (these methods are added by `meteor-coverage` on the client side), which runs an HTTP request to the server to tells `meteor-coverage` to create the dump on the disk. Otherwise the coverage report in the memory. Tip: `exportCoverage` will use the `.coverage.json` to know where it needs to store the dump.

> Ok i'll take a look at your repo, you were having issues with spacejam I assume?

Spacejam doesn't run tests once it detects a `console.error`, which is used when a test fails. If `meteor-todo` outputs some error on boot you can't run spacejam on it.

**Comment by serut** [comment]
Now meteor-coverage use `meteortesting` package to run CI tests, you can use another headless browser like chrome. It should fix this type of issue so I close it.
