### ISSUE TITLE
Switching from the deprecated istanbul-api to istanbuljs

### ISSUE THREAD

**Issue by SimonSimCity** [serut/meteor-coverage#53]
Are there plans switching from [`istanbul-api`](https://github.com/istanbuljs/istanbul-api) to [istanbuljs](https://github.com/istanbuljs/istanbuljs)?

This might also be related to https://github.com/istanbuljs/nyc/issues/648, since the possibility to run meteor using `nyc` directly would (in my eyes) deprecate this repository in itself 😉

**Comment by serut** [comment]
No you cannot run `nyc` on top of meteor because meteor only runs the compilation on its thread. Then, it creates another thread with your app... `nyc` is not designed to handle such process fork.  
My lib runs `istanbul-api` on runtime, which looks like the only way to collect coverage...! 
To sum up : 
- `nyc` runs your app and when stopped collects the coverage. If you want to see what meteor code is used to compile your project you can try. No way that nyc understand that your frontend should be covered. 
-  `istanbuljs` looks quite similar to `istanbul-api`, but first update `istanbul-api` to its last version before going to `istanbuljs`

I do not plan to update meteor-coverage as I am not working on meteor app right now, but if you want to try, your PR would be welcome !

**Comment by hexsprite** [comment]
I got nyc working with Meteor just fine, but it requires to invoke Meteor without the bootstrap script.

Details here:

https://forums.meteor.com/t/using-istanbul-nyc-for-code-coverage-in-meteor/38258
