### ISSUE TITLE
JQuery package dependency is not loaded

### ISSUE THREAD

**Issue by xolott** [serut/meteor-coverage#88]
I added this package to my project, and everything works as expected when doing tests. But when I run the app normally, it shows console errors. If I remove this package, everything returns to normal

## Expected Behavior

It should work without any issue

## Current Behavior

It shows an error:
![image](https://user-images.githubusercontent.com/5204776/147961491-3a108a02-de3c-438f-ac68-b0ac7459f41f.png)

## Your Environment

* Version used: lmieulet:meteor-coverage@1.1.4
* Environment name and version: Node 14.18.2 and Meteor 2.5
* Operating System and version: Ubuntu 20.04

**Comment by serut** [comment]
Hmm, strange. Can you try to upgrade lmieulet:meteor-coverage@1.1.4, as there is 3.2.0 available

Maybe I can publish a version of meteor coverage with `testOnly ` instead of [`debugOnly`](https://github.com/serut/meteor-coverage/blob/master/package.js#L7) - https://docs.meteor.com/api/packagejs.html#PackageNamespace-describe

**Comment by xolott** [comment]
Thank you! I don't know why, but meteor installed an old version. I had to force the update to the specific version (4.1.0)

Everything works fine
